### ISSUE TITLE
License terms

### ISSUE THREAD

**Issue by mthebridge** [jjo/docker-jinja2-cli#1]
Hi @jjo - found this container on docker hub and it looks very useful as a lightweight jinja2 environment.

However I can't see a license anywhere here or on DockerHub - would you be willing to release this under a permissive license such as MIT, so others can freely use it?

Many thanks!

**Comment by jjo** [comment]
hi @mthebridge, sure noprob will add an APACHE 2.0 license.
Regards --jjo

**Comment by mthebridge** [comment]
Great - thank you!
